services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: nba
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2.5
    ports:
      - "6379:6379"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    ports:
      - "2181:2181"

  stats-service:
    build: ./stats-service
    depends_on:
      - db
      - kafka
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: nba
      KAFKA_BROKER: kafka:9092
      REDIS_HOST: redis:6379
    ports:
      - "8080:8080"

  aggregation-service:
    build: ./aggregation-service
    depends_on:
      - db
      - kafka
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: nba
      KAFKA_BROKER: kafka:9092
      REDIS_HOST: redis:6379
    ports:
      - "8081:8081"