// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Stat struct {
	ID            int32
	PlayerID      int32
	TeamID        int32
	Points        int32
	Rebounds      int32
	Assists       int32
	Steals        int32
	Blocks        int32
	Fouls         int32
	Turnovers     int32
	MinutesPlayed float64
	CreatedAt     pgtype.Timestamp
}
